spring:
  datasource:
    url: jdbc:mysql:///withjpa?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
#    database: mysql
#    database-platform: mysql